name: Deploy app

on:
  push:
    branches:
      - git-hub-action

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
        
      - name: echo test
        run: echo "Hi"